/******************************************************************************/
/**** 1. TTIPODOCUMENTO (Apenas CPF e CNPJ)                                ****/
/******************************************************************************/
INSERT INTO TTIPODOCUMENTO (BDDESCDOCUMENTO) VALUES ('CPF');  -- ID 1
INSERT INTO TTIPODOCUMENTO (BDDESCDOCUMENTO) VALUES ('CNPJ'); -- ID 2

/******************************************************************************/
/**** 2. TUF (10 Estados)                                                  ****/
/******************************************************************************/
INSERT INTO TUF (BDDESCUF) VALUES ('SC'); -- ID 1
INSERT INTO TUF (BDDESCUF) VALUES ('PR'); -- ID 2
INSERT INTO TUF (BDDESCUF) VALUES ('SP'); -- ID 3
INSERT INTO TUF (BDDESCUF) VALUES ('RJ'); -- ID 4
INSERT INTO TUF (BDDESCUF) VALUES ('MG'); -- ID 5
INSERT INTO TUF (BDDESCUF) VALUES ('RS'); -- ID 6
INSERT INTO TUF (BDDESCUF) VALUES ('BA'); -- ID 7
INSERT INTO TUF (BDDESCUF) VALUES ('PE'); -- ID 8
INSERT INTO TUF (BDDESCUF) VALUES ('GO'); -- ID 9
INSERT INTO TUF (BDDESCUF) VALUES ('MT'); -- ID 10

/******************************************************************************/
/**** 3. TALIQUOTAICMS (10 Alíquotas vinculadas às UFs)                     ****/
/******************************************************************************/
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (17.00, 1);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (18.00, 2);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (18.00, 3);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (12.00, 4);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (12.00, 5);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (17.50, 6);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (19.00, 7);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (18.00, 8);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (17.00, 9);
INSERT INTO TALIQUOTAICMS (BDALIQUOTA, BDCODUF) VALUES (17.00, 10);

/******************************************************************************/
/**** 4. TALIQUOTAFEDERAL (10 Registros)                                   ****/
/******************************************************************************/
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2026, 1.65, 7.60);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2025, 1.65, 7.60);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2024, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2023, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2022, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2021, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2020, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2019, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2018, 0.65, 3.00);
INSERT INTO TALIQUOTAFEDERAL (BDANO, BDALIQUOTAPIS, BDALIQUOTACOFINS) VALUES (2017, 0.65, 3.00);

/******************************************************************************/
/**** 5. TCIDADE (10 Cidades vinculadas corretamente às UFs)               ****/
/******************************************************************************/
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Blumenau', 1);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Curitiba', 2);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Sao Paulo', 3);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Rio de Janeiro', 4);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Belo Horizonte', 5);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Porto Alegre', 6);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Salvador', 7);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Recife', 8);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Goiania', 9);
INSERT INTO TCIDADE (BDDESCCIDADE, BDCODUF) VALUES ('Cuiaba', 10);

/******************************************************************************/
/**** 6. TCLIENTE (10 Clientes - IDs batendo com Cidades e Tipos)          ****/
/******************************************************************************/
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Ana Silva', '47999991111', 'Rua XV de Novembro, 10', '12345678901', 1, 1);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Bruno Souza', '41999992222', 'Av. Sete de Setembro, 200', '98765432100', 1, 2);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Carlos Tech', '11999993333', 'Av. Paulista, 1500', '11222333000199', 2, 3);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Daniela Lima', '21999994444', 'Av. Atlantica, 450', '44455566677', 1, 4);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Eduardo Alves', '31999995555', 'Rua da Bahia, 300', '55566677788', 1, 5);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Fernanda Loja', '51999996666', 'Av. Ipiranga, 90', '22333444000188', 2, 6);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Gabriel Costa', '71999997777', 'Av. Tancredo Neves, 50', '77788899900', 1, 7);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Helena Modas', '81999998888', 'Rua do Hospicio, 120', '33444555000177', 2, 8);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Igor Santos', '62999999999', 'Av. T-63, 800', '99900011122', 1, 9);
INSERT INTO TCLIENTE (BDNOMECLIENTE, BDTELEFONECLIENTE, BDENDERECOCLIENTE, BDDOCUMENTOCLIENTE, BDCODTIPODOCUMENTO, BDCODCIDADE) VALUES ('Julia Ramos', '65999990000', 'Av. do CPA, 1100', '00011122233', 1, 10);

/******************************************************************************/
/**** 7. TPRODUTO (10 Produtos)                                            ****/
/******************************************************************************/
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (101, 'Notebook Gamer', 4500.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (102, 'Smartphone 5G', 2500.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (103, 'Monitor Ultrawide 29', 1200.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (104, 'Teclado Mecanico RGB', 350.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (105, 'Mouse Sem Fio Ergonomico', 180.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (106, 'Headset Gamer 7.1', 400.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (107, 'Cadeira Escritorio Mesh', 850.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (108, 'Roteador Wi-Fi 6', 450.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (109, 'SSD M.2 NVMe 1TB', 500.00);
INSERT INTO TPRODUTO (BDIDENTIFCOMERCIAL, BDDESCPRODUTO, BDPRECOPRODUTO) VALUES (110, 'Memoria RAM DDR4 16GB', 380.00);

/******************************************************************************/
/**** 8. TNOTAFISCAL (10 Notas Fiscais)                                    ****/
/******************************************************************************/
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-15', 1001, 1, 4500, 1);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-16', 1002, 1, 2500, 2);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-17', 1003, 1, 1200, 3);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-18', 1004, 1, 350,  4);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-19', 1005, 1, 180,  5);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-20', 1006, 1, 400,  6);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-21', 1007, 1, 850,  7);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-22', 1008, 1, 450,  8);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-23', 1009, 1, 500,  9);
INSERT INTO TNOTAFISCAL (BDDATAEMISSAO, BDNUMDOCUMENTO, BDSERIEDOCUMENTO, BDVALORTOTAL, BDCODCLIENTE) VALUES ('2026-06-24', 1010, 1, 380,  10);

/******************************************************************************/
/**** 9. TNOTAFISCALITEM (10 Itens vinculados perfeitamente)                ****/
/******************************************************************************/
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 4500.00, 4500.00, 1, 1);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 2500.00, 2500.00, 2, 2);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 1200.00, 1200.00, 3, 3);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 350.00,  350.00,  4, 4);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 180.00,  180.00,  5, 5);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 400.00,  400.00,  6, 6);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 850.00,  850.00,  7, 7);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 450.00,  450.00,  8, 8);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 500.00,  500.00,  9, 9);
INSERT INTO TNOTAFISCALITEM (BDQTDPRODUTO, BDPRECOUNITARIO, BDVALORTOTALITEM, BDCODNOTA, BDCODPRODUTO) VALUES (1, 380.00,  380.00,  10, 10);

COMMIT;

