/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN DM_NOME100 AS
VARCHAR(100)
COLLATE WIN_PTBR;

CREATE DOMAIN DM_NOME50 AS
VARCHAR(50)
COLLATE WIN_PTBR;

CREATE DOMAIN DM_NOME80 AS
VARCHAR(80)
COLLATE WIN_PTBR;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TARBITROS (
    BDCODARBITRO  INTEGER NOT NULL,
    BDNOME        DM_NOME100 NOT NULL,
    BDPAISORIGEM  DM_NOME80 NOT NULL
);

CREATE TABLE TCONTINENTES (
    BDCODCONTINENTE  INTEGER NOT NULL,
    BDNOME           DM_NOME50 NOT NULL
);

CREATE TABLE TESTADIOS (
    BDCODESTADIO  INTEGER NOT NULL,
    BDNOME        DM_NOME100 NOT NULL,
    BDCIDADE      DM_NOME80 NOT NULL,
    BDCAPACIDADE  INTEGER NOT NULL
);

CREATE TABLE TFASES (
    BDCODFASE    INTEGER NOT NULL,
    BDDESCRICAO  DM_NOME50 NOT NULL
);

CREATE TABLE TJOGOS (
    BDCODJOGO     INTEGER NOT NULL,
    BDCODFASE     INTEGER NOT NULL,
    BDCODESTADIO  INTEGER NOT NULL,
    BDCODARBITRO  INTEGER NOT NULL,
    BDDATAJOGO    DATE NOT NULL,
    BDHORARIO     TIME NOT NULL
);

CREATE TABLE TJOGOSELECOES (
    BDCODJOGOSELECAO      INTEGER NOT NULL,
    BDCODJOGO             INTEGER NOT NULL,
    BDCODSELECAO          INTEGER NOT NULL,
    BDCODTIPOSELECAOJOGO  INTEGER NOT NULL,
    BDGOLS                INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE TJOGOSELECOES2 (
    BDCODJOGOSELECAO  INTEGER NOT NULL,
    BDCODJOGO         INTEGER NOT NULL,
    BDCODSELECAO_M    INTEGER NOT NULL,
    BDGOLS_M          INTEGER DEFAULT 0 NOT NULL,
    BDCODSELECAO_V    INTEGER NOT NULL,
    BDGOLS_V          INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE TSELECOES (
    BDCODSELECAO     INTEGER NOT NULL,
    BDCODCONTINENTE  INTEGER NOT NULL,
    BDNOME           DM_NOME80 NOT NULL,
    BDNOMETECNICO    DM_NOME100
);

CREATE TABLE TTIPOSSELECAOJOGO (
    BDCODTIPOSELECAOJOGO  INTEGER NOT NULL,
    BDDESCRICAO           DM_NOME50 NOT NULL
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TARBITROS ADD CONSTRAINT PK_TARBITROS PRIMARY KEY (BDCODARBITRO);
ALTER TABLE TCONTINENTES ADD CONSTRAINT PK_TCONTINENTES PRIMARY KEY (BDCODCONTINENTE);
ALTER TABLE TESTADIOS ADD CONSTRAINT PK_TESTADIOS PRIMARY KEY (BDCODESTADIO);
ALTER TABLE TFASES ADD CONSTRAINT PK_TFASES PRIMARY KEY (BDCODFASE);
ALTER TABLE TJOGOS ADD CONSTRAINT PK_TJOGOS PRIMARY KEY (BDCODJOGO);
ALTER TABLE TJOGOSELECOES ADD CONSTRAINT PK_TJOGOSELECOES PRIMARY KEY (BDCODJOGOSELECAO);
ALTER TABLE TJOGOSELECOES2 ADD CONSTRAINT PK_TJOGOSELECOES2 PRIMARY KEY (BDCODJOGOSELECAO);
ALTER TABLE TSELECOES ADD CONSTRAINT PK_TSELECOES PRIMARY KEY (BDCODSELECAO);
ALTER TABLE TTIPOSSELECAOJOGO ADD CONSTRAINT PK_TTIPOSSELECAOJOGO PRIMARY KEY (BDCODTIPOSELECAOJOGO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TJOGOS ADD CONSTRAINT FK_TJOGOS_TARBITROS FOREIGN KEY (BDCODARBITRO) REFERENCES TARBITROS (BDCODARBITRO);
ALTER TABLE TJOGOS ADD CONSTRAINT FK_TJOGOS_TESTADIOS FOREIGN KEY (BDCODESTADIO) REFERENCES TESTADIOS (BDCODESTADIO);
ALTER TABLE TJOGOS ADD CONSTRAINT FK_TJOGOS_TFASES FOREIGN KEY (BDCODFASE) REFERENCES TFASES (BDCODFASE);
ALTER TABLE TJOGOSELECOES ADD CONSTRAINT FK_TJOGOSELECOES_TJOGOS FOREIGN KEY (BDCODJOGO) REFERENCES TJOGOS (BDCODJOGO);
ALTER TABLE TJOGOSELECOES ADD CONSTRAINT FK_TJOGOSELECOES_TSELECOES FOREIGN KEY (BDCODSELECAO) REFERENCES TSELECOES (BDCODSELECAO);
ALTER TABLE TJOGOSELECOES ADD CONSTRAINT FK_TJOGOSELECOES_TTIPOSSELECAOJOGO FOREIGN KEY (BDCODTIPOSELECAOJOGO) REFERENCES TTIPOSSELECAOJOGO (BDCODTIPOSELECAOJOGO);
ALTER TABLE TJOGOSELECOES2 ADD CONSTRAINT FK_TJOGOSELECOES2_TJOGOS FOREIGN KEY (BDCODJOGO) REFERENCES TJOGOS (BDCODJOGO);
ALTER TABLE TJOGOSELECOES2 ADD CONSTRAINT FK_TJOGOSELECOES2_TSELECOES FOREIGN KEY (BDCODSELECAO_M) REFERENCES TSELECOES (BDCODSELECAO);
ALTER TABLE TJOGOSELECOES2 ADD CONSTRAINT FK_TJOGOSELECOES2_TSELECOES2 FOREIGN KEY (BDCODSELECAO_V) REFERENCES TSELECOES (BDCODSELECAO);
ALTER TABLE TSELECOES ADD CONSTRAINT FK_TSELECOES_TCONTINENTES FOREIGN KEY (BDCODCONTINENTE) REFERENCES TCONTINENTES (BDCODCONTINENTE);
